deps: Update mininum support to Python 3.8, Pandas 1.5.0, Numpy 1.20.3
googleapis/python-db-dtypes-pandas pull request #286
Opened 2024-07-31 20:33 UTC by chelsea-lin

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-db-dtypes-pandas/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-07-31 21:44 UTC, tswast commented
Looks like `unit (3.7)` is still marked as required. Could you send a PR creating a sync-repo-setting.yml first? The if one isn't created then, this is used: https://github.com/googleapis/repo-automation-bots/blob/19bb823389a77e22d00371cb53ecadab4a58ab9e/packages/sync-repo-settings/src/required-checks.json#L50

2024-08-01 16:43 UTC, tswast reviewed
Let's update https://github.com/googleapis/python-db-dtypes-pandas/blob/main/.github/workflows/unittest.yml to drop 3.7 too.

Might need to exclude that file in https://github.com/googleapis/python-db-dtypes-pandas/blob/main/owlbot.py until we drop Python 3.7 google-wide.

2024-08-16 18:09 UTC, Linchin commented
@chalmerlowe has been working on an effort to drop support for python 3.7 and 3.8 (see internal doc go/drop-python-37). We likely will need to drop the support in sync with that.

2025-01-17 20:09 UTC, tswast commented on testing/constraints-3.7.txt
Since we are removing this, please update constraints-3.9.txt to include all the minimum versions from setup.py

2025-01-28 15:22 UTC, chalmerlowe requested changes
If possible, please also remove all references to `Python 3.8`, since we have approval to deprecate support for that version as well as 3.7.

I did a comprehensive review of all the files in the repo to find any references to `3.` since there may be conditionals such as: 
`< 3.9` or `<= 3.9` and because there may be references to things that are no longer needed if support for a specific version of Python is dropped. 

The following files have content that needs to be corrected OR reviewed for correctness AND/OR deleted.

```
* CONTRIBUTING.rst (multiple references, including instructions that guide users to use 3.8)
* noxfile.py (references 3.8)
* samples/snippets/noxfile.py (references 3.8)
* owlbot.py
* pytest.ini (references removing code once we drop support for 3.7 and 3.8)
* python-db-dtypes-pandas/README.rst (references supported versions of Python)
* docs/README.rst (references supported versions of Python) (probably autogenerated by sphinx
  so maybe no action needed)
* setup.py (references 3.8)
* sync-repo-settings.yaml (CI/CD checks related to 3.8)
* lint.yml (references 3.8)
* unittest.yml (references 3.8)
* test-samples-impl.sh (references using an older version of virtualenv to maintain 3.7 compatibility)
  #NOTE I think I have a version of virtualenv that will work. I will try to get that version
  (if memory serves, the latest version does not work so we need a slightly older one).
* .kokoro/samples/python3.7/common.cfg (whole directory for 3.7)
* .kokoro/samples/python3.8/common.cfg (whole directory for 3.8)
* db_dtypes/__init__.py
  * references need for an older version of pandas if using 3.7 and does a conditional check
    for that version of pandas
  * includes a warning indicating that Python 3.7 and 3.8 are deprecated and does a check
    for Python version
* samples/snippets/requirements-test.txt (references 3.7/>3.7)
* install_deps.tmpl.rst (references 3.7+)
* constraints-3.8.txt (delete)
```

If you have questions about a specific change, please reach out.

2025-02-12 14:58 UTC, chalmerlowe commented
In discussion with Chelsea and our respective workloads, Linchin or I (prolly me, since I am working Python deprecation issues elsewhere as well) will be taking over this PR to help shepherd it to completion.

@chelsea-lin 
@Linchin

2025-05-19 10:41 UTC, chalmerlowe commented
Superceded by #337 (and ancillary PRs).
Closing.

2025-05-19 10:41 UTC, closed without merging